# dependencies only
version: "3.9"

# Network configuration
networks:
  transcoorditor:
    external: true
    name: transcoorditor

# Service configuration
services:

  mongodb:
    container_name: mongodb
    image: "mongo:4"
    ports:
      - 27017:27017
    # links:
    #   - mongo1
    #   - mongo2
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - ./.local/data:/data/db

  # mongo1:
  #   container_name: mongo1
  #   image: "mongo:4"
  #   ports:
  #     - 27018:27017
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  #   volumes:
  #     - ./.local/data1:/data/db
  #
  # mongo2:
  #   container_name: mongo2
  #   image: "mongo:4"
  #   ports:
  #     - 27019:27017
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  #   volumes:
  #     - ./.local/data2:/data/db

  transcoorditor:
    build: .
    container_name: transcoorditor
    environment:
      # - MONGODB_URI=mongodb://mongodb:27017,mongo1:27017,mongo2:27017/?replicaSet=rs0
      - MONGODB_URI=mongodb://mongodb:27017
      - BOLTDB_PATH=/bolt/bolt.db
      # - BACKEND_STORE=mongodb
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    volumes:
      - ./.local/bolt:/bolt
    networks:
      - default
      - transcoorditor

