# dependencies only
version: "3.9"

x-baseservice: &baseservice
  build: .
  networks:
    - default
    - transcoorditor

x-common-env: &common-env
  - DEBUG_LEVEL=debug
  - PORT=8000
  - SERVER_READ_TIMEOUT=300
  - CLUSTER_BASE_DIR=/cluster
  - RAFT_DB=raft.db

# Network configuration
networks:
  transcoorditor:
    external: true
    name: transcoorditor

# Service configuration
services:

  mongodb:
    container_name: mongodb
    image: "mongo:4"
    ports:
      - 27017:27017
    # links:
    #   - mongo1
    #   - mongo2
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - ./.local/mongodb/data:/data/db

  # mongo1:
  #   container_name: mongo1
  #   image: "mongo:4"
  #   ports:
  #     - 27018:27017
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  #   volumes:
  #     - ./.local/data1:/data/db
  #
  # mongo2:
  #   container_name: mongo2
  #   image: "mongo:4"
  #   ports:
  #     - 27019:27017
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  #   volumes:
  #     - ./.local/data2:/data/db

  transcoorditor1:
    <<: *baseservice
    container_name: transcoorditor1
    environment:
      - NODE_ADDR=transcoorditor1:7000
      - NODE_ID=transcoorditor1
      - BACKEND_STORE=boltdb
      - MONGODB_URI=mongodb://mongodb:27017
      - BOLTDB_PATH=/cluster/bolt.db
    depends_on:
      - mongodb
    ports:
      - "8001:8000"
      - "7001:7000"
    volumes:
      - ./.local/cluster1:/cluster
    networks:
      - default
      - transcoorditor

  transcoorditor2:
    <<: *baseservice
    container_name: transcoorditor2
    environment:
      - NODE_ADDR=transcoorditor2:7000
      - NODE_ID=transcoorditor2
      - BACKEND_STORE=mongodb
      # - MONGODB_URI=mongodb://mongodb:27017,mongo1:27017,mongo2:27017/?replicaSet=rs0
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=transcoorditor2
    depends_on:
      - mongodb
    ports:
      - "8002:8000"
      - "7002:7000"
    volumes:
      - ./.local/cluster2:/cluster
    networks:
      - default
      - transcoorditor

  transcoorditor3:
    <<: *baseservice
    container_name: transcoorditor3
    environment:
      - NODE_ADDR=transcoorditor3:7000
      - NODE_ID=transcoorditor3
      - BACKEND_STORE=boltdb
      - MONGODB_URI=mongodb://mongodb:27017
      - BOLTDB_PATH=/cluster/bolt.db
    depends_on:
      - mongodb
    ports:
      - "8003:8000"
      - "7003:7000"
    volumes:
      - ./.local/cluster3:/cluster
    networks:
      - default
      - transcoorditor
